version: "3.3"
services:
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ~/deluge:/config
      - /home/you/tor-downloads:/tor-download
      - /data-lake:/data-lake
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    links:
      - sabnzbd
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dns_ext.rule=Host(`dns.your.site`)"
      - "traefik.http.routers.dns_ext.entrypoints=websecure"
      - "traefik.http.routers.dns_ext.tls.certresolver=digitalocean"
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ~/radarr:/config
      - /home/you/sab-downloads:/sab-download
      - /data-lake:/data-lake
    ports:
      - 7878:7878
    links:
      - sabnzbd
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`movies.your.site`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=digitalocean"
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ~/sab:/config
      - /home/you/sab-downloads:/sab-download
      - /data-lake:/data-lake
    ports:
      - 8081:8080
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sab.rule=Host(`sab.your.site`)"
      - "traefik.http.routers.sab.entrypoints=websecure"
      - "traefik.http.routers.sab.tls.certresolver=digitalocean"
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ~/lidarr:/config
      - /home/you/sab-downloads:/sab-download
      - /data-lake:/data-lake
    ports:
      - 8686:8686
    links:
      - sabnzbd
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.rule=Host(`music.your.site`)"
      - "traefik.http.routers.lidarr.entrypoints=websecure"
      - "traefik.http.routers.lidarr.tls.certresolver=digitalocean"
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ~/sonarr:/config
      - /home/you/sab-downloads:/sab-download
      - /data-lake:/data-lake
    ports:
      - 8989:8989
    links:
      - sabnzbd
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`tv.your.site`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=digitalocean"
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - HOSTNAME=data-lake
      - ADVERTISE_IP=https://plex.your.site:443
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - NVIDIA_VISIBLE_DEVICES=GPU-473224b8-4016-f6ef-106e-0a3d566eabbe
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex-lake.your.site`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.tls.certresolver=digitalocean"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
    ports:
      - 32400:32400/tcp
      - 32400:32400/udp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1901:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ~/plex-lake:/config
      - /data-lake/tv-too:/tv-too
      - /data-lake/tv:/tv
      - /data-lake/movies:/movies
      - /data-lake/data/porn:/porn-static
      - /home/you/sab-downloads:/sab-download
      - /data-lake:/data-lake
      - /dev/shm:/transcode
    runtime: nvidia
  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.digitalocean.acme.dnschallenge=true"
      - "--certificatesresolvers.digitalocean.acme.dnschallenge.provider=digitalocean"
      - "--certificatesresolvers.digitalocean.acme.email=root@hweeks.com"
      - "--certificatesresolvers.digitalocean.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
